### PR TITLE
Enable PIE

### PR DESCRIPTION
**Pull request by adamjhogan**
Build busybox to work on Android 5.*

### CODE REVIEW

**Comment by SDkie** [comment]
@godlessfather : Have you tested it on both Android4.\* and Android5.\* ?

**Comment by adamjhogan** [comment]
Sorry, I was only worrying about 5. I didn't bother to check 4. CANNOT LINK EXECUTABLE: cannot locate symbol "tcsetattr" on 4.*

**Comment by eighthave** [comment]
This build should work on `android-16` and newer, i.e. Android 4.1. How about doing the fully static build of `busybox`? I wonder if that will be huge.

**Comment by eighthave** [comment]
also, its probably better to post pull requests to the main fork, to make them more visible:
https://github.com/guardianproject/lildebi

**Comment by SDkie** [comment]
@eighthave : we can try that, but currently I don't have rooted Android L to test it.

**Pull request closed without merging**
